"""
Django settings for swaggerpetstore project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-4q)qin(z2kkg4)22xc88kkaf7w-b*3lasy0j&#(aa%5tx@t82="

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "pets",
    "stores",
    "users",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "swaggerpetstore.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "swaggerpetstore.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Override the default user model
# https://docs.djangoproject.com/en/4.1/topics/auth/customizing/#substituting-a-custom-user-model

AUTH_USER_MODEL = "users.User"

# Absolute filesystem path to the directory that will hold user-uploaded files
# https://docs.djangoproject.com/en/4.1/ref/settings/#std-setting-MEDIA_ROOT
# https://docs.djangoproject.com/en/4.1/ref/settings/#std-setting-MEDIA_URL

MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# MEDIA_URL = "media/"

# Setting authentication scheme
# https://www.django-rest-framework.org/api-guide/authentication/#how-authentication-is-determined

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
}

# drf-spectacular settings
# https://drf-spectacular.readthedocs.io/en/latest/readme.html#installation

SPECTACULAR_SETTINGS = {
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX_TRIM": True,
    "TITLE": "Swagger Petstore - OpenAPI 3.0",
    "DESCRIPTION": "This is a sample Pet Store Server based on the OpenAPI 3.0 specification. \
                    You can find out more about Swagger at [https://swagger.io](https://swagger.io). \
                    In the third iteration of the pet store, we've switched to the design first approach! \
                    You can now help us improve the API whether it's by making changes to the definition \
                    itself or to the code. That way, with time, we can improve the API in general, and \
                    expose some of the new features in OAS3. \
                    \n \
                    \n If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click \
                    [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). \
                    Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option! \
                    \n \
                    \n Some useful links: \
                    \n - [The Pet Store repository](https://github.com/vsraccubits/swagger-petstore)",
    "TOS": "http://swagger.io/terms/",
    "CONTACT": {"email": "varun.sr@accubits.com"},
    "LICENSE": {
        "name": "Apache 2.0",
        "url": "http://www.apache.org/licenses/LICENSE-2.0",
    },
    "VERSION": "1.0.0",
    "SERVERS": [{"url": "http://localhost:8000/api/v1"}],
    "TAGS": [
        {
            "name": "pet",
            "description": "Everything about your Pets",
            "externalDocs": {
                "description": "Find out more",
                "url": "http://swagger.io",
            },
        },
        {
            "name": "store",
            "description": "Access to Petstore orders",
            "externalDocs": {
                "description": "Find out more about our store",
                "url": "http://swagger.io",
            },
        },
        {"name": "user", "description": "Operations about user"},
    ],
    "EXTERNAL_DOCS": {
        "url": "https://docs.google.com/document/d/1vtj2gmCNfnIYF3SM13QGJZD2SAFzLtGVEtpD9-uKSos/edit?usp=sharing",
        "description": "Find out more about OpenAPI3",
    },
    "POSTPROCESSING_HOOKS": [],
    "SORT_OPERATION_PARAMETERS": False,
}
