# Generated by Django 4.1.2 on 2022-10-10 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('zip', models.CharField(max_length=100, verbose_name='Zip')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Order Quantity')),
                ('ship_date', models.DateTimeField(auto_now_add=True, verbose_name='Order Date Time')),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('approved', 'Approved'), ('delivered', 'Delivered')], default='placed', max_length=30, verbose_name='Order Status')),
                ('complete', models.BooleanField(default=False, verbose_name='Order Complete')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pets.pet', verbose_name='Order Pet')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Customer Username')),
                ('addresses', models.ManyToManyField(to='stores.address', verbose_name='Customer Addresses')),
            ],
        ),
    ]
